%% Dengue-Pneumonia Co-infection Model with Control (Vector-driven Dengue)
function dengue_model_with_control_Tasmia
clear; clc;

%% Simulation time
tspan = [0 250]; % days

%% Initial conditions
S0 = 1000; Ed0 = 10; Id0 = 30; Rd0 = 0;
Ep0 = 10; Ip0 = 20; Rp0 = 0;
Idp0 = 0; V0 = 0; 
Sv0 = 5000; Ev0 = 10; Iv0 = 5;

y0 = [S0, Ed0, Id0, Rd0, Ep0, Ip0, Rp0, Idp0, V0, Sv0, Ev0, Iv0];

%% Baseline parameters
Lambda_h = 2000; Lambda_v = 5000;
mu_h = 1/(72*365); mu_v = 0.1;

beta_d = 0.15; beta_p = 0.08; beta_v = 0.7; b = 0.5;
gamma_d = 1/5.5; gamma_p = 1/3; gamma_v = 1/10;

tau_d = 1/7; tau_p = 1/14; tau_dp = 1/25;
delta_d = 0.001; delta_p = 0.005; delta_dp = 0.03;

omega_d = 1/180; omega_p = 1/(2*365);

rho_dp = 2.2; rho_pd = 1.5;
phi_d = 0.5; phi_p = 0.6;

epsilon_p = 1.5; epsilon_dv = 1.2;

sigma_d = 0.3; sigma_p = 0.4; sigma_v = 0.3;
alpha_d = 0.001; alpha_p = 0.002;

% Intervention controls (0=no, 1=full)
%c = 0.01; m = 0.01; l = 0.01; kappa_v = 0.1;
%c = 0.3; m = 0.3; l = 0.5; kappa_v = 0.8; %strong control
c = 0.15; m = 0.2; l = 0.2; kappa_v = 0.3; %moderate control

%% Effective parameters under control
beta_d_eff = beta_d*(1-c)*(1-m);
beta_p_eff = beta_p*(1-c);
beta_v_eff = beta_v*(1-kappa_v)*(1-l);
Lambda_v_eff = Lambda_v*(1-l);

%% =========================
%% WITHOUT CONTROL
%% =========================
ode_fun_no_control = @(t,y) dengue_model_vector(t,y,...
    beta_d,beta_p,beta_v,b,Lambda_h,Lambda_v,...
    gamma_d,gamma_p,gamma_v,...
    tau_d,tau_p,tau_dp,...
    delta_d,delta_p,delta_dp,...
    mu_h,mu_v,...
    rho_dp,rho_pd,phi_d,phi_p,...
    epsilon_p,epsilon_dv,...
    sigma_d,sigma_p,sigma_v,...
    alpha_d,alpha_p);

[t1,Y1] = ode45(ode_fun_no_control,tspan,y0);

%% =========================
%% WITH CONTROL
%% =========================
ode_fun_control = @(t,y) dengue_model_vector(t,y,...
    beta_d_eff,beta_p_eff,beta_v_eff,b,Lambda_h,Lambda_v_eff,...
    gamma_d,gamma_p,gamma_v,...
    tau_d,tau_p,tau_dp,...
    delta_d,delta_p,delta_dp,...
    mu_h,mu_v,...
    rho_dp,rho_pd,phi_d,phi_p,...
    epsilon_p,epsilon_dv,...
    sigma_d,sigma_p,sigma_v,...
    alpha_d,alpha_p);

[t2,Y2] = ode45(ode_fun_control,tspan,y0);

%% =========================
%% Plot results
%% =========================
figure;

plot(t1,Y1(:,3),'r--','LineWidth',1.5); hold on; % Id
plot(t2,Y2(:,3),'r','LineWidth',2);

plot(t1,Y1(:,6),'b--','LineWidth',1.5); % Ip
plot(t2,Y2(:,6),'b','LineWidth',2);

% plot(t1,Y1(:,8),'m--','LineWidth',1.5); % Idp
% plot(t2,Y2(:,8),'m','LineWidth',2);

%plot(t1,Y1(:,12),'k--','LineWidth',1.5); % Iv
%plot(t2,Y2(:,12),'k','LineWidth',2);

xlabel('Time (days)','FontSize', 13);
ylabel('Infected populations','FontSize', 13);
title('Dengue & Pneumonia  infected populations with moderate control intervations','FontSize', 13);
%title('Dengue & Pneumonia  infected populations with Strong control intervations','FontSize', 13);
legend('Id (no control)','Id (control)',...
       'Ip (no control)','Ip (control)',...
       'Iv (no control)','Iv (control)',...
       'Location','northeast');
   set(gca, 'FontSize', 13, 'LineWidth', 2);
%legend('Id (no control)','Id (control)',...
%       'Ip (no control)','Ip (control)',...
%       'Idp (no control)','Idp (control)',...
%       'Iv (no control)','Iv (control)',...
%       'Location','northeast');
grid on;

%% =========================================================
%% ODE FUNCTION
%% =========================================================
end
function dy = dengue_model_vector(~,y,...
    beta_d,beta_p,beta_v,b,Lambda_h,Lambda_v,...
    gamma_d,gamma_p,gamma_v,...
    tau_d,tau_p,tau_dp,...
    delta_d,delta_p,delta_dp,...
    mu_h,mu_v,...
    rho_dp,rho_pd,phi_d,phi_p,...
    epsilon_p,epsilon_dv,...
    sigma_d,sigma_p,sigma_v,...
    alpha_d,alpha_p)

    % States
    S = y(1); Ed = y(2); Id = y(3); Rd = y(4);
    Ep = y(5); Ip = y(6); Rp = y(7); Idp = y(8);
    V = y(9); Sv = y(10); Ev = y(11); Iv = y(12);

    Nh = S + Ed + Id + Rd + Ep + Ip + Rp + Idp + V;

    %% Human dynamics
    dS = Lambda_h ...
        - beta_d*(Iv/Nh)*S ...
        - beta_p*(Ip + epsilon_p*Idp)/Nh*S ...
        - (mu_h + alpha_d + alpha_p)*S;

    dEd = beta_d*(Iv/Nh)*(S + sigma_p*Rp + sigma_v*V) ...
        - (gamma_d + mu_h)*Ed ...
        - rho_dp*beta_p*(Ip + epsilon_p*Idp)/Nh*Ed;

    dId = gamma_d*Ed ...
        - (mu_h + delta_d + tau_d)*Id ...
        - rho_dp*beta_p*(Ip + epsilon_p*Idp)/Nh*Id;

    dRd = tau_d*Id ...
        - mu_h*Rd ...
        - phi_d*beta_p*(Ip + epsilon_p*Idp)/Nh*Rd;

    dEp = beta_p*(Ip + epsilon_p*Idp)/Nh*(S + sigma_d*Rd + sigma_v*V) ...
        - (gamma_p + mu_h)*Ep ...
        - rho_pd*beta_d*(Iv/Nh)*Ep;

    dIp = gamma_p*Ep ...
        - (mu_h + delta_p + tau_p)*Ip ...
        - rho_pd*beta_d*(Iv/Nh)*Ip;

    dRp = tau_p*Ip ...
        - mu_h*Rp ...
        - phi_p*beta_d*(Iv/Nh)*Rp;

    dIdp = rho_dp*beta_p*(Ip + epsilon_p*Idp)/Nh*(Ed + Id) ...
         + rho_pd*beta_d*(Iv/Nh)*(Ep + Ip) ...
         + phi_d*beta_p*(Ip + epsilon_p*Idp)/Nh*Rd ...
         + phi_p*beta_d*(Iv/Nh)*Rp ...
         - (mu_h + delta_dp + tau_dp)*Idp;

    dV = alpha_d*S + alpha_p*S ...
        - mu_h*V ...
        - sigma_v*beta_d*(Iv/Nh)*V ...
        - sigma_v*beta_p*(Ip + epsilon_p*Idp)/Nh*V;

    %% Mosquito dynamics
    dSv = Lambda_v ...
        - beta_v*b*(Id + epsilon_dv*Idp)/Nh*Sv ...
        - mu_v*Sv;

    dEv = beta_v*b*(Id + epsilon_dv*Idp)/Nh*Sv ...
        - (gamma_v + mu_v)*Ev;

    dIv = gamma_v*Ev - mu_v*Iv;

    %% Combine
    dy = [dS; dEd; dId; dRd; dEp; dIp; dRp; dIdp; dV; dSv; dEv; dIv];
end